import { FeatureItem } from "@/components/ui/features-section";

export const wealthFeatures: FeatureItem[] = [
  {
    id: "01",
    title: "Investment Products",
    description: "Diverse investment options curated to match risk profiles, financial goals, and time horizons for sustainable wealth growth.",
    image: "/placeholder.jpg",
    imageAlt: "Investment Products",
    layout: "image-left",
  },
  {
    id: "02",
    title: "Mutual Funds (MFs)",
    description: "Access to SIPs, lump-sum investments, and diversified portfolios across equity, debt, and hybrid categories for steady wealth creation.",
    image: "/placeholder.jpg",
    imageAlt: "Mutual Funds",
    layout: "image-right",
  },
  {
    id: "03",
    title: "AIFs & PMS",
    description: "Exclusive investment strategies through Alternative Investment Funds and Portfolio Management Services designed for HNIs and UHNWIs.",
    image: "/placeholder.jpg",
    imageAlt: "AIFs & PMS",
    layout: "image-left",
  },
  {
    id: "04",
    title: "Fixed-Income Products",
    description: "Secure investment avenues including corporate bonds, NCDs, and government securities offering stable and predictable returns.",
    image: "/placeholder.jpg",
    imageAlt: "Fixed-Income Products",
    layout: "image-right",
  },
  {
    id: "05",
    title: "Structured Products",
    description: "Innovative investment instruments combining safety and performance through capital protection and yield-enhancement features.",
    image: "/placeholder.jpg",
    imageAlt: "Structured Products",
    layout: "image-left",
  },
  {
    id: "06",
    title: "Advisory & Planning",
    description: "Personalized financial advisory tailored to your life goals, risk appetite, and long-term wealth-building objectives.",
    image: "/placeholder.jpg",
    imageAlt: "Advisory & Planning",
    layout: "image-right",
  },
  {
    id: "07",
    title: "Goal-Based Wealth Planning",
    description: "Comprehensive planning for retirement, children's education, and legacy creation with disciplined, purpose-driven investment strategies.",
    image: "/placeholder.jpg",
    imageAlt: "Goal-Based Wealth Planning",
    layout: "image-left",
  },
  {
    id: "08",
    title: "Family Office Setup & Succession Planning",
    description: "End-to-end support in establishing family offices, managing multi-generational wealth, and ensuring smooth succession transitions.",
    image: "/placeholder.jpg",
    imageAlt: "Family Office Setup & Succession Planning",
    layout: "image-right",
  },
  {
    id: "09",
    title: "Portfolio Review & Rebalancing",
    description: "Regular performance assessment and rebalancing to maintain portfolio alignment with market trends and financial objectives.",
    image: "/placeholder.jpg",
    imageAlt: "Portfolio Review & Rebalancing",
    layout: "image-left",
  },
];

