import { FeatureItem } from "@/components/ui/features-section";

export const insuranceFeatures: FeatureItem[] = [
  {
    id: "01",
    title: "Life Insurance",
    description: "Comprehensive life protection solutions designed to secure families, safeguard income, and ensure long-term financial stability.",
    image: "/placeholder.jpg",
    imageAlt: "Life Insurance",
    layout: "image-left",
  },
  {
    id: "02",
    title: "Term Plans, ULIPs, Child & Retirement Plans",
    description: "Flexible insurance-cum-investment options offering life cover, wealth creation, and future planning for children and retirement goals.",
    image: "/placeholder.jpg",
    imageAlt: "Term Plans, ULIPs, Child & Retirement Plans",
    layout: "image-right",
  },
  {
    id: "03",
    title: "Group & Corporate Life Covers",
    description: "Customized group life insurance programs providing affordable protection and benefits for employees and corporate teams.",
    image: "/placeholder.jpg",
    imageAlt: "Group & Corporate Life Covers",
    layout: "image-left",
  },
  {
    id: "04",
    title: "General Insurance",
    description: "Wide-ranging coverage to protect individuals and businesses from financial losses arising from unforeseen risks and damages.",
    image: "/placeholder.jpg",
    imageAlt: "General Insurance",
    layout: "image-right",
  },
  {
    id: "05",
    title: "Health, Motor, Fire, Marine, Property & Travel",
    description: "Comprehensive protection across multiple categories ensuring safety, recovery support, and peace of mind for all life and business needs.",
    image: "/placeholder.jpg",
    imageAlt: "Health, Motor, Fire, Marine, Property & Travel",
    layout: "image-left",
  },
  {
    id: "06",
    title: "Group Mediclaim for Corporates & MSMEs",
    description: "Affordable, scalable healthcare insurance solutions that safeguard employee well-being and enhance workplace satisfaction.",
    image: "/placeholder.jpg",
    imageAlt: "Group Mediclaim for Corporates & MSMEs",
    layout: "image-right",
  },
  {
    id: "07",
    title: "Credit-Linked Insurance",
    description: "Tailored protection plans linked to loans, minimizing financial burden on families and lenders in case of unforeseen events.",
    image: "/placeholder.jpg",
    imageAlt: "Credit-Linked Insurance",
    layout: "image-left",
  },
  {
    id: "08",
    title: "Loan Protection for BL/LAP/HL Clients",
    description: "Specialized insurance coverage for Finvastra clients securing business, property, and home loan repayments against life uncertainties.",
    image: "/placeholder.jpg",
    imageAlt: "Loan Protection for BL/LAP/HL Clients",
    layout: "image-right",
  },
  {
    id: "09",
    title: "Integrated Insurance Issuance at Loan Disbursal",
    description: "Seamless integration of insurance issuance with loan processing to ensure instant coverage and convenience for clients.",
    image: "/placeholder.jpg",
    imageAlt: "Integrated Insurance Issuance at Loan Disbursal",
    layout: "image-left",
  },
];

